# .github/workflows/frontend.yml

name: Frontend CI Checks

# MODIFICAÇÃO: O workflow agora roda APENAS em Pull Requests para a 'main'.
# A Vercel cuidará do deploy no push para a 'main'.
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'packages/web/**'
      - '.github/workflows/frontend.yml'

jobs:
  # O job de build foi mantido para garantir a integridade do código
  build-and-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/web

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: packages/web/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Check build
        run: npm run build
        env:
          # Para as checagens, podemos usar a URL da API de desenvolvimento ou uma de testes
          NEXT_PUBLIC_API_URL: http://localhost:5257

# MODIFICAÇÃO: O job 'deploy' foi completamente removido.
# A Vercel cuidará do deploy de produção e de preview automaticamente.